FROM python:3.6


WORKDIR /api
COPY . /api/

RUN apt-get update && apt-get install -y libmagic-dev

EXPOSE 5000

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install coverage
